"""add prize rule uniqueness

Revision ID: 167f2fd921ca
Revises: 7719f1c8a552
Create Date: 2026-09-04 08:03:22.783689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167f2fd921ca'
down_revision: Union[str, Sequence[str], None] = '7719f1c8a552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prize_rule_config_wins', 'prize_rules', ['game_config_id', 'required_wins'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prize_rule_config_wins', 'prize_rules', type_='unique')
    # ### end Alembic commands ###
