"""add admin login rate limiting

Revision ID: 56532c751d48
Revises: 0dd9982f84c0
Create Date: 2026-09-24 19:19:19.650340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56532c751d48'
down_revision: Union[str, Sequence[str], None] = '0dd9982f84c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_login_attempts_ip_address'), 'admin_login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_admin_login_attempts_username'), 'admin_login_attempts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_login_attempts_username'), table_name='admin_login_attempts')
    op.drop_index(op.f('ix_admin_login_attempts_ip_address'), table_name='admin_login_attempts')
    op.drop_table('admin_login_attempts')
    # ### end Alembic commands ###
