"""create prize rules

Revision ID: 7719f1c8a552
Revises: a6d4e18e1826
Create Date: 2026-09-04 00:49:59.705511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7719f1c8a552'
down_revision: Union[str, Sequence[str], None] = 'a6d4e18e1826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_config_id', sa.Integer(), nullable=False),
    sa.Column('required_wins', sa.Integer(), nullable=False),
    sa.Column('prize_name', sa.String(length=100), nullable=False),
    sa.Column('prize_image_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_config_id'], ['game_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prize_rules')
    # ### end Alembic commands ###
